sudo: true
language: haskell

git:
  depth: 5

cabal: "2.4"

cache:
  directories:
  - "$HOME/.cabal/store"
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"

matrix:
  include:

  # # Cabal
  # - ghc: 8.2.2
  # - ghc: 8.4.4
  # - ghc: 8.6.5

  # Stack
  - ghc: 8.6.5

install:
  # install stack
  - curl -sSL https://get.haskellstack.org/ | sh
  - stack --version
  - stack build

script:
    stack test

notifications:
  email: false
