name:                haskell-snap-realworld-example-app
version:             0.1.0.0
github:              "kigsmtua/haskell-snap-realworld-example-app"
license:             MIT
author:              "John Kiragu"
maintainer:          "mutuakiragu@gmail.com"
copyright:           "2019 John Kiragu"

extra-source-files:
- README.md
- ChangeLog.md

description: Please see the README on GitHub at <https://github.com/kigsmtua/haskell-snap-realworld-example-app#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring >= 0.9.1 && < 0.11
- mtl >= 2 && < 3
- aeson
- persistent-sqlite
- persistent
- persistent-template
- monad-control
- monad-logger
- text
- esqueleto
- snap-core >= 1.0 && < 1.1
- snap-server >= 1.0 && < 1.2
- time
- resourcet

library:
  source-dirs: src

executables:
  haskell-snap-realworld-example-app-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -funbox-strict-fields
    dependencies:
    - haskell-snap-realworld-example-app

tests:
  conduit-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - conduit
